package br.com.sysmap.backend.model.enums;

public enum AchievementType {
    FIRST_ACTIVITY_CREATED,
    FIRST_SUBSCRIPTION,
    FIRST_CHECKIN,
    FIVE_ACTIVITIES_PARTICIPATED,
    TEN_ACTIVITIES_PARTICIPATED,
    FIVE_CHECKINS,
    TEN_CHECKINS,
    FIVE_ACTIVITIES_CREATED,
    TEN_ACTIVITIES_CREATED,
    ONE_HUNDRED_XP
}
