spring:
  application:
    name: api

  datasource:
    url: jdbc:postgresql://localhost:5432/bootcamp
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
        default_schema: public

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

logging:
  level:
    liquibase: DEBUG

aws:
  s3:
    bucket: profile-images
    endpoint: http://localhost:4566
    region: us-east-1
    access-key: test
    secret-key: test
